// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// This query performs a "soft delete" by changing the status to 'cancelled'.
	// We never truly delete data, we just change its state.
	CancelNotification(ctx context.Context, id pgtype.UUID) (Notification, error)
	// This query inserts a new notification into the database.
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// This query retrieves a single notification by its unique UUID.
	GetNotificationByID(ctx context.Context, id pgtype.UUID) (Notification, error)
	// This query updates the status, attempts count, and sent_at timestamp of a notification.
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (Notification, error)
}

var _ Querier = (*Queries)(nil)
